name: "🚀 Publish Node.js Package"
on:
  push:
    branches:
      - master
jobs:
  build:
    name: "Publish @dnt-ticketing-mvc/common 🚀"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npm run pub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
